# Generated by Django 5.2.13 on 2026-05-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('node_type', models.CharField(choices=[('command', 'Kommando'), ('unit', 'Enhed'), ('patrol', 'Patrulje')], default='unit', max_length=20, verbose_name='type')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first among siblings.', verbose_name='display order')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_nodes', to=settings.AUTH_USER_MODEL, verbose_name='leader')),
                ('members', models.ManyToManyField(blank=True, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='members')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hierarchy.node', verbose_name='parent node')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
