# Generated by Django 5.2.13 on 2026-04-12 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='first name')),
                ('cognome', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('telefono', models.CharField(max_length=20, verbose_name='phone number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('generated_password', models.CharField(blank=True, max_length=128, verbose_name='generated password')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
            ],
            options={
                'verbose_name': 'join request',
                'verbose_name_plural': 'join requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
