# Generated by Django 5.2.13 on 2026-04-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_italian_fields_to_english'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, help_text='ISO code (e.g. DNK, ITA)', max_length=3, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('cpt', 'CPT'), ('1lt', '1LT'), ('2lt', '2LT'), ('sgt1c', 'SGT 1C'), ('ssgt', 'SSGT'), ('sgt', 'SGT'), ('cpl', 'CPL'), ('spc', 'SPC'), ('pvt1', 'PVT 1'), ('pvt2', 'PVT 2'), ('pvt', 'PVT')], default='pvt', max_length=20, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='place of residence'),
        ),
    ]
