# Generated by Django 5.2.13 on 2026-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_profile_image_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('gen', 'GEN'), ('cpt', 'CPT'), ('1lt', '1LT'), ('2lt', '2LT'), ('sgt1c', 'SGT 1C'), ('ssgt', 'SSGT'), ('sgt', 'SGT'), ('cpl', 'CPL'), ('spc', 'SPC'), ('pvt1', 'PVT 1'), ('pvt2', 'PVT 2'), ('pvt', 'PVT')], default='pvt', max_length=20, verbose_name='rank'),
        ),
    ]
