# Generated by Django 5.2.13 on 2026-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_gen_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('gen', 'GEN'), ('cpt', 'CPT'), ('1lt', '1LT'), ('2lt', '2LT'), ('sgt1c', 'SGT 1C'), ('ssgt', 'SSGT'), ('sgt', 'SGT'), ('cpl', 'CPL'), ('spc', 'SPC'), ('pvt1', 'PVT 1'), ('pvt2', 'PVT 2'), ('pvt', 'PVT')], max_length=20, unique=True, verbose_name='rank')),
                ('icon', models.ImageField(help_text='Rank insignia image (95×170 px WebP).', upload_to='ranks/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'rank icon',
                'verbose_name_plural': 'rank icons',
                'ordering': ['rank'],
            },
        ),
    ]
