# Generated by Django 5.2.13 on 2026-07-25 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_phone_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='verification token')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'pending verification',
                'verbose_name_plural': 'pending verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
