# Generated by Django 5.2.13 on 2026-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='award_mode',
        ),
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='rule_config',
        ),
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='info',
            field=models.TextField(blank=True, help_text='Hvorfor dette achievement gives.'),
        ),
    ]
