# Generated by Django 5.2.13 on 2026-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_remove_achievementdefinition_award_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='description',
        ),
    ]
