# Generated by Django 5.2.13 on 2026-05-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Billede af udstyret (maks. 5 MB, komprimeres automatisk til WebP).', null=True, upload_to='armoury/')),
                ('category', models.CharField(choices=[('aeg', 'AEG (Automatisk elektrisk gevær)'), ('gbb', 'GBB (Gas Blowback)'), ('springer', 'Molla (Springer)'), ('hpa', 'HPA (High Pressure Air)'), ('accessories', 'Tilbehør'), ('clothing', 'Beklædning')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_equipment', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
