# Generated by Django 5.2.13 on 2026-04-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Forsidebillede (maks. 5 MB, komprimeres automatisk til WebP).', null=True, upload_to='manual_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_ranks', models.CharField(blank=True, help_text='Kommasepareret liste over rang-koder der må læse manualen, f.eks. "gen,cpt,1lt". Lad feltet stå tomt for alle.', max_length=200)),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manualer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Supports HTML markup.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Laveste tal vises først.')),
                ('image', models.ImageField(blank=True, help_text='Valgfrit illustrationsbillede til kapitlet (WebP komprimeres automatisk).', null=True, upload_to='manual_chapters/')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manuals.manual')),
            ],
            options={
                'verbose_name': 'Kapitel',
                'verbose_name_plural': 'Kapitler',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
