# Generated by Django 5.2.13 on 2026-07-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactical', '0002_make_bounds_nullable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpawnPoint',
        ),
    ]
