# Generated by Django 5.2.13 on 2026-07-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.TextField(help_text='Beskriv hvad udgiften dækker, og hvorfor den er nødvendig.', verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Afventer'), ('approved', 'Godkendt'), ('rejected', 'Afvist'), ('clarification_requested', 'Afventer afklaring')], default='pending', max_length=30, verbose_name='status')),
                ('admin_message', models.TextField(blank=True, help_text='Besked fra admin (f.eks. anmodning om flere oplysninger).', verbose_name='admin message')),
                ('admin_response', models.TextField(blank=True, help_text='Svar fra brugeren på admins besked.', verbose_name='user response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'expense request',
                'verbose_name_plural': 'expense requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_finance_permissions', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_permission', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'finance view permission',
                'verbose_name_plural': 'finance view permissions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Indtægt'), ('expense', 'Udgift')], max_length=10, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('note', models.TextField(blank=True, verbose_name='internal note')),
                ('expense_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.expenserequest', verbose_name='expense request')),
                ('incurred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incurred_transactions', to=settings.AUTH_USER_MODEL, verbose_name='incurred by')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
